package com.vismay.membersportal.services;

import com.vismay.membersportal.databeans.FilesUploadDataBean;
import com.vismay.membersportal.databeans.MarqueeDataBean;
import com.vismay.membersportal.databeans.MemberRegistrationDatabean;
import com.vismay.membersportal.databeans.UserRegistrationDataBean;
import com.vismay.membersportal.exceptions.FileStorageException;
import com.vismay.membersportal.exceptions.MyFileNotFoundException;
import com.vismay.membersportal.repositories.RegisterMemberDao;
import com.vismay.membersportal.repositories.UserRegistrationDao;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Random;

@Service
public class RegisterMemberService {

    @Autowired
    private RegisterMemberDao registerMemberDao;

    @Autowired
    private UserRegistrationDao userRegistrationDao;

    @Autowired
    private DBFileStorageService dbFileStorageService;

    public MemberRegistrationDatabean saveMember(MemberRegistrationDatabean memberRegistrationDatabean, MultipartFile multipartFile) throws FileStorageException {
        FilesUploadDataBean filesUploadDataBean = dbFileStorageService.storeFile(multipartFile);
        memberRegistrationDatabean.setImage(filesUploadDataBean.getId());
        memberRegistrationDatabean.setStatus("Active");

        UserRegistrationDataBean dataBean=new UserRegistrationDataBean();
        dataBean.setFullName(memberRegistrationDatabean.getFullName());
        dataBean.setEmailId(memberRegistrationDatabean.getEmailAddress());
        String autoGeneratedString=generateRandomString(10);
        dataBean.setUsername(autoGeneratedString);
        dataBean.setPassword(autoGeneratedString);
        dataBean.setMobileNo(memberRegistrationDatabean.getMobileNo());
        dataBean.setEnabled("1");
        dataBean.setUserRole("member");
        System.out.printf("Member"+dataBean);
        userRegistrationDao.save(dataBean);


        return registerMemberDao.save(memberRegistrationDatabean);
    }

    public String generateRandomString(int count){
        String ALPHA_NUMERIC_STRING = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            StringBuilder builder = new StringBuilder();
            while (count-- != 0) {
                int character = (int)(Math.random()*ALPHA_NUMERIC_STRING.length());
                builder.append(ALPHA_NUMERIC_STRING.charAt(character));
            }
            return builder.toString();
    }


    public List<MemberRegistrationDatabean> getAllMemberList() {
        return registerMemberDao.findAll();
    }

    public MemberRegistrationDatabean getMemberFromId(Long id) {
        return registerMemberDao.findById(id).get();
    }

    public MemberRegistrationDatabean updateMember(MemberRegistrationDatabean memberRegistrationDatabean, MultipartFile multipartFile) throws FileStorageException, MyFileNotFoundException {
        FilesUploadDataBean filesUploadDataBean;

        if (!multipartFile.isEmpty()){
            filesUploadDataBean = dbFileStorageService.storeFile(multipartFile);
            memberRegistrationDatabean.setImage(filesUploadDataBean.getId());
        }else{
            filesUploadDataBean = dbFileStorageService.getFile(memberRegistrationDatabean.getImage());
            memberRegistrationDatabean.setImage(filesUploadDataBean.getId());
        }

        return registerMemberDao.save(memberRegistrationDatabean);
    }

    public List<String> getAllVillages() {
        return registerMemberDao.getAllVillages();
    }

    public List<String> getAllStreets() {
        return registerMemberDao.getAllStreets();
    }

    public List<MemberRegistrationDatabean> getMemberData(String village, String street, String mobileNo, String pinCode) {
        return registerMemberDao.getMemberData(village,street,mobileNo,pinCode);
    }
}
